// Generated by tests/transform-testdata.ts
export const fixtureData = [
  {
    "caseIndex": 0,
    "pattern": [
      {
        "pathname": "/foo/bar"
      }
    ],
    "input": {
      "pathname": "/foo/bar"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo/bar"
  },
  {
    "caseIndex": 4,
    "pattern": [
      {
        "pathname": "/foo/bar"
      }
    ],
    "input": "https://example.com/foo/bar",
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {
        "0": "https"
      },
      "hostname": {
        "0": "example.com"
      },
      "port": {}
    },
    "expectedUrl": "https://example.com/foo/bar"
  },
  {
    "caseIndex": 6,
    "pattern": [
      {
        "pathname": "/foo/bar"
      }
    ],
    "input": {
      "hostname": "example.com",
      "pathname": "/foo/bar"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {
        "0": "example.com"
      },
      "port": {}
    },
    "expectedUrl": "http://example.com/foo/bar"
  },
  {
    "caseIndex": 8,
    "pattern": [
      {
        "pathname": "/foo/bar"
      }
    ],
    "input": {
      "pathname": "/foo/bar",
      "baseURL": "https://example.com"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {
        "0": "https"
      },
      "hostname": {
        "0": "example.com"
      },
      "port": {}
    },
    "expectedUrl": "https://example.com/foo/bar"
  },
  {
    "caseIndex": 12,
    "pattern": [
      {
        "pathname": "/foo/bar",
        "baseURL": "https://example.com?query#hash"
      }
    ],
    "input": {
      "protocol": "https",
      "hostname": "example.com",
      "pathname": "/foo/bar"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "https://example.com/foo/bar"
  },
  {
    "caseIndex": 13,
    "pattern": [
      {
        "pathname": "/foo/bar",
        "baseURL": "https://example.com"
      }
    ],
    "input": {
      "protocol": "https",
      "hostname": "example.com",
      "pathname": "/foo/bar"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "https://example.com/foo/bar"
  },
  {
    "caseIndex": 15,
    "pattern": [
      {
        "pathname": "/foo/bar",
        "baseURL": "https://example.com?query#hash"
      }
    ],
    "input": {
      "protocol": "https",
      "hostname": "example.com",
      "pathname": "/foo/bar",
      "search": "otherquery",
      "hash": "otherhash"
    },
    "params": {
      "pathname": {},
      "search": {
        "0": "otherquery"
      },
      "hash": {
        "0": "otherhash"
      },
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "https://example.com/foo/bar?otherquery#otherhash"
  },
  {
    "caseIndex": 16,
    "pattern": [
      {
        "pathname": "/foo/bar",
        "baseURL": "https://example.com"
      }
    ],
    "input": {
      "protocol": "https",
      "hostname": "example.com",
      "pathname": "/foo/bar",
      "search": "otherquery",
      "hash": "otherhash"
    },
    "params": {
      "pathname": {},
      "search": {
        "0": "otherquery"
      },
      "hash": {
        "0": "otherhash"
      },
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "https://example.com/foo/bar?otherquery#otherhash"
  },
  {
    "caseIndex": 17,
    "pattern": [
      {
        "pathname": "/foo/bar",
        "baseURL": "https://example.com?otherquery#otherhash"
      }
    ],
    "input": {
      "protocol": "https",
      "hostname": "example.com",
      "pathname": "/foo/bar",
      "search": "otherquery",
      "hash": "otherhash"
    },
    "params": {
      "pathname": {},
      "search": {
        "0": "otherquery"
      },
      "hash": {
        "0": "otherhash"
      },
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "https://example.com/foo/bar?otherquery#otherhash"
  },
  {
    "caseIndex": 18,
    "pattern": [
      {
        "pathname": "/foo/bar",
        "baseURL": "https://example.com?query#hash"
      }
    ],
    "input": "https://example.com/foo/bar",
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "https://example.com/foo/bar"
  },
  {
    "caseIndex": 19,
    "pattern": [
      {
        "pathname": "/foo/bar",
        "baseURL": "https://example.com?query#hash"
      }
    ],
    "input": "https://example.com/foo/bar?otherquery#otherhash",
    "params": {
      "pathname": {},
      "search": {
        "0": "otherquery"
      },
      "hash": {
        "0": "otherhash"
      },
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "https://example.com/foo/bar?otherquery#otherhash"
  },
  {
    "caseIndex": 20,
    "pattern": [
      {
        "pathname": "/foo/bar",
        "baseURL": "https://example.com?query#hash"
      }
    ],
    "input": "https://example.com/foo/bar?query#hash",
    "params": {
      "pathname": {},
      "search": {
        "0": "query"
      },
      "hash": {
        "0": "hash"
      },
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "https://example.com/foo/bar?query#hash"
  },
  {
    "caseIndex": 24,
    "pattern": [
      {
        "pathname": "/foo/bar",
        "baseURL": "https://example.com?query#hash"
      }
    ],
    "input": {
      "pathname": "/foo/bar",
      "baseURL": "https://example.com"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "https://example.com/foo/bar"
  },
  {
    "caseIndex": 25,
    "pattern": [
      {
        "pathname": "/foo/bar",
        "baseURL": "https://example.com?query#hash"
      }
    ],
    "input": {
      "pathname": "/foo/bar",
      "baseURL": "https://example.com?query#hash"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "https://example.com/foo/bar?query#hash"
  },
  {
    "caseIndex": 29,
    "pattern": [
      {
        "pathname": "/foo/:bar"
      }
    ],
    "input": {
      "pathname": "/foo/bar"
    },
    "params": {
      "pathname": {
        "bar": "bar"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo/bar"
  },
  {
    "caseIndex": 30,
    "pattern": [
      {
        "pathname": "/foo/([^\\/]+?)"
      }
    ],
    "input": {
      "pathname": "/foo/bar"
    },
    "params": {
      "pathname": {
        "0": "bar"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo/bar"
  },
  {
    "caseIndex": 31,
    "pattern": [
      {
        "pathname": "/foo/:bar"
      }
    ],
    "input": {
      "pathname": "/foo/index.html"
    },
    "params": {
      "pathname": {
        "bar": "index.html"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo/index.html"
  },
  {
    "caseIndex": 34,
    "pattern": [
      {
        "pathname": "/foo/(.*)"
      }
    ],
    "input": {
      "pathname": "/foo/bar"
    },
    "params": {
      "pathname": {
        "0": "bar"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo/bar"
  },
  {
    "caseIndex": 35,
    "pattern": [
      {
        "pathname": "/foo/*"
      }
    ],
    "input": {
      "pathname": "/foo/bar"
    },
    "params": {
      "pathname": {
        "0": "bar"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo/bar"
  },
  {
    "caseIndex": 36,
    "pattern": [
      {
        "pathname": "/foo/(.*)"
      }
    ],
    "input": {
      "pathname": "/foo/bar/baz"
    },
    "params": {
      "pathname": {
        "0": "bar/baz"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo/bar/baz"
  },
  {
    "caseIndex": 37,
    "pattern": [
      {
        "pathname": "/foo/*"
      }
    ],
    "input": {
      "pathname": "/foo/bar/baz"
    },
    "params": {
      "pathname": {
        "0": "bar/baz"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo/bar/baz"
  },
  {
    "caseIndex": 38,
    "pattern": [
      {
        "pathname": "/foo/(.*)"
      }
    ],
    "input": {
      "pathname": "/foo/"
    },
    "params": {
      "pathname": {
        "0": ""
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo/"
  },
  {
    "caseIndex": 39,
    "pattern": [
      {
        "pathname": "/foo/*"
      }
    ],
    "input": {
      "pathname": "/foo/"
    },
    "params": {
      "pathname": {
        "0": ""
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo/"
  },
  {
    "caseIndex": 42,
    "pattern": [
      {
        "pathname": "/foo/:bar(.*)"
      }
    ],
    "input": {
      "pathname": "/foo/bar"
    },
    "params": {
      "pathname": {
        "bar": "bar"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo/bar"
  },
  {
    "caseIndex": 43,
    "pattern": [
      {
        "pathname": "/foo/:bar(.*)"
      }
    ],
    "input": {
      "pathname": "/foo/bar/baz"
    },
    "params": {
      "pathname": {
        "bar": "bar/baz"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo/bar/baz"
  },
  {
    "caseIndex": 44,
    "pattern": [
      {
        "pathname": "/foo/:bar(.*)"
      }
    ],
    "input": {
      "pathname": "/foo/"
    },
    "params": {
      "pathname": {
        "bar": ""
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo/"
  },
  {
    "caseIndex": 46,
    "pattern": [
      {
        "pathname": "/foo/:bar?"
      }
    ],
    "input": {
      "pathname": "/foo/bar"
    },
    "params": {
      "pathname": {
        "bar": "bar"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo/bar"
  },
  {
    "caseIndex": 47,
    "pattern": [
      {
        "pathname": "/foo/:bar?"
      }
    ],
    "input": {
      "pathname": "/foo"
    },
    "params": {
      "pathname": {
        "bar": null
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo"
  },
  {
    "caseIndex": 51,
    "pattern": [
      {
        "pathname": "/foo/:bar+"
      }
    ],
    "input": {
      "pathname": "/foo/bar"
    },
    "params": {
      "pathname": {
        "bar": "bar"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo/bar"
  },
  {
    "caseIndex": 52,
    "pattern": [
      {
        "pathname": "/foo/:bar+"
      }
    ],
    "input": {
      "pathname": "/foo/bar/baz"
    },
    "params": {
      "pathname": {
        "bar": "bar/baz"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo/bar/baz"
  },
  {
    "caseIndex": 56,
    "pattern": [
      {
        "pathname": "/foo/:bar*"
      }
    ],
    "input": {
      "pathname": "/foo/bar"
    },
    "params": {
      "pathname": {
        "bar": "bar"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo/bar"
  },
  {
    "caseIndex": 57,
    "pattern": [
      {
        "pathname": "/foo/:bar*"
      }
    ],
    "input": {
      "pathname": "/foo/bar/baz"
    },
    "params": {
      "pathname": {
        "bar": "bar/baz"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo/bar/baz"
  },
  {
    "caseIndex": 58,
    "pattern": [
      {
        "pathname": "/foo/:bar*"
      }
    ],
    "input": {
      "pathname": "/foo"
    },
    "params": {
      "pathname": {
        "bar": null
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo"
  },
  {
    "caseIndex": 61,
    "pattern": [
      {
        "pathname": "/foo/(.*)?"
      }
    ],
    "input": {
      "pathname": "/foo/bar"
    },
    "params": {
      "pathname": {
        "0": "bar"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo/bar"
  },
  {
    "caseIndex": 62,
    "pattern": [
      {
        "pathname": "/foo/*?"
      }
    ],
    "input": {
      "pathname": "/foo/bar"
    },
    "params": {
      "pathname": {
        "0": "bar"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo/bar"
  },
  {
    "caseIndex": 63,
    "pattern": [
      {
        "pathname": "/foo/(.*)?"
      }
    ],
    "input": {
      "pathname": "/foo/bar/baz"
    },
    "params": {
      "pathname": {
        "0": "bar/baz"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo/bar/baz"
  },
  {
    "caseIndex": 64,
    "pattern": [
      {
        "pathname": "/foo/*?"
      }
    ],
    "input": {
      "pathname": "/foo/bar/baz"
    },
    "params": {
      "pathname": {
        "0": "bar/baz"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo/bar/baz"
  },
  {
    "caseIndex": 65,
    "pattern": [
      {
        "pathname": "/foo/(.*)?"
      }
    ],
    "input": {
      "pathname": "/foo"
    },
    "params": {
      "pathname": {
        "0": null
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo"
  },
  {
    "caseIndex": 66,
    "pattern": [
      {
        "pathname": "/foo/*?"
      }
    ],
    "input": {
      "pathname": "/foo"
    },
    "params": {
      "pathname": {
        "0": null
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo"
  },
  {
    "caseIndex": 67,
    "pattern": [
      {
        "pathname": "/foo/(.*)?"
      }
    ],
    "input": {
      "pathname": "/foo/"
    },
    "params": {
      "pathname": {
        "0": ""
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo/"
  },
  {
    "caseIndex": 68,
    "pattern": [
      {
        "pathname": "/foo/*?"
      }
    ],
    "input": {
      "pathname": "/foo/"
    },
    "params": {
      "pathname": {
        "0": ""
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo/"
  },
  {
    "caseIndex": 73,
    "pattern": [
      {
        "pathname": "/foo/(.*)+"
      }
    ],
    "input": {
      "pathname": "/foo/bar"
    },
    "params": {
      "pathname": {
        "0": "bar"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo/bar"
  },
  {
    "caseIndex": 74,
    "pattern": [
      {
        "pathname": "/foo/*+"
      }
    ],
    "input": {
      "pathname": "/foo/bar"
    },
    "params": {
      "pathname": {
        "0": "bar"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo/bar"
  },
  {
    "caseIndex": 75,
    "pattern": [
      {
        "pathname": "/foo/(.*)+"
      }
    ],
    "input": {
      "pathname": "/foo/bar/baz"
    },
    "params": {
      "pathname": {
        "0": "bar/baz"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo/bar/baz"
  },
  {
    "caseIndex": 76,
    "pattern": [
      {
        "pathname": "/foo/*+"
      }
    ],
    "input": {
      "pathname": "/foo/bar/baz"
    },
    "params": {
      "pathname": {
        "0": "bar/baz"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo/bar/baz"
  },
  {
    "caseIndex": 79,
    "pattern": [
      {
        "pathname": "/foo/(.*)+"
      }
    ],
    "input": {
      "pathname": "/foo/"
    },
    "params": {
      "pathname": {
        "0": ""
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo/"
  },
  {
    "caseIndex": 80,
    "pattern": [
      {
        "pathname": "/foo/*+"
      }
    ],
    "input": {
      "pathname": "/foo/"
    },
    "params": {
      "pathname": {
        "0": ""
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo/"
  },
  {
    "caseIndex": 85,
    "pattern": [
      {
        "pathname": "/foo/(.*)*"
      }
    ],
    "input": {
      "pathname": "/foo/bar"
    },
    "params": {
      "pathname": {
        "0": "bar"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo/bar"
  },
  {
    "caseIndex": 86,
    "pattern": [
      {
        "pathname": "/foo/**"
      }
    ],
    "input": {
      "pathname": "/foo/bar"
    },
    "params": {
      "pathname": {
        "0": "bar"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo/bar"
  },
  {
    "caseIndex": 87,
    "pattern": [
      {
        "pathname": "/foo/(.*)*"
      }
    ],
    "input": {
      "pathname": "/foo/bar/baz"
    },
    "params": {
      "pathname": {
        "0": "bar/baz"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo/bar/baz"
  },
  {
    "caseIndex": 88,
    "pattern": [
      {
        "pathname": "/foo/**"
      }
    ],
    "input": {
      "pathname": "/foo/bar/baz"
    },
    "params": {
      "pathname": {
        "0": "bar/baz"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo/bar/baz"
  },
  {
    "caseIndex": 89,
    "pattern": [
      {
        "pathname": "/foo/(.*)*"
      }
    ],
    "input": {
      "pathname": "/foo"
    },
    "params": {
      "pathname": {
        "0": null
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo"
  },
  {
    "caseIndex": 90,
    "pattern": [
      {
        "pathname": "/foo/**"
      }
    ],
    "input": {
      "pathname": "/foo"
    },
    "params": {
      "pathname": {
        "0": null
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo"
  },
  {
    "caseIndex": 91,
    "pattern": [
      {
        "pathname": "/foo/(.*)*"
      }
    ],
    "input": {
      "pathname": "/foo/"
    },
    "params": {
      "pathname": {
        "0": ""
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo/"
  },
  {
    "caseIndex": 92,
    "pattern": [
      {
        "pathname": "/foo/**"
      }
    ],
    "input": {
      "pathname": "/foo/"
    },
    "params": {
      "pathname": {
        "0": ""
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo/"
  },
  {
    "caseIndex": 97,
    "pattern": [
      {
        "pathname": "/foo{/bar}"
      }
    ],
    "input": {
      "pathname": "/foo/bar"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo/bar"
  },
  {
    "caseIndex": 101,
    "pattern": [
      {
        "pathname": "/foo{/bar}?"
      }
    ],
    "input": {
      "pathname": "/foo/bar"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo/bar"
  },
  {
    "caseIndex": 103,
    "pattern": [
      {
        "pathname": "/foo{/bar}?"
      }
    ],
    "input": {
      "pathname": "/foo"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo"
  },
  {
    "caseIndex": 105,
    "pattern": [
      {
        "pathname": "/foo{/bar}+"
      }
    ],
    "input": {
      "pathname": "/foo/bar"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo/bar"
  },
  {
    "caseIndex": 106,
    "pattern": [
      {
        "pathname": "/foo{/bar}+"
      }
    ],
    "input": {
      "pathname": "/foo/bar/bar"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo/bar/bar"
  },
  {
    "caseIndex": 110,
    "pattern": [
      {
        "pathname": "/foo{/bar}*"
      }
    ],
    "input": {
      "pathname": "/foo/bar"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo/bar"
  },
  {
    "caseIndex": 111,
    "pattern": [
      {
        "pathname": "/foo{/bar}*"
      }
    ],
    "input": {
      "pathname": "/foo/bar/bar"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo/bar/bar"
  },
  {
    "caseIndex": 113,
    "pattern": [
      {
        "pathname": "/foo{/bar}*"
      }
    ],
    "input": {
      "pathname": "/foo"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo"
  },
  {
    "caseIndex": 122,
    "pattern": [
      {
        "protocol": ":café"
      }
    ],
    "input": {
      "protocol": "foo"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {
        "café": "foo"
      },
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/"
  },
  {
    "caseIndex": 123,
    "pattern": [
      {
        "username": ":café"
      }
    ],
    "input": {
      "username": "foo"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {
        "café": "foo"
      },
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://foo@example.com/"
  },
  {
    "caseIndex": 124,
    "pattern": [
      {
        "password": ":café"
      }
    ],
    "input": {
      "password": "foo"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {
        "café": "foo"
      },
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://:foo@example.com/"
  },
  {
    "caseIndex": 125,
    "pattern": [
      {
        "hostname": ":café"
      }
    ],
    "input": {
      "hostname": "foo"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {
        "café": "foo"
      },
      "port": {}
    },
    "expectedUrl": "http://foo/"
  },
  {
    "caseIndex": 126,
    "pattern": [
      {
        "pathname": "/:café"
      }
    ],
    "input": {
      "pathname": "/foo"
    },
    "params": {
      "pathname": {
        "café": "foo"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo"
  },
  {
    "caseIndex": 127,
    "pattern": [
      {
        "search": ":café"
      }
    ],
    "input": {
      "search": "foo"
    },
    "params": {
      "pathname": {},
      "search": {
        "café": "foo"
      },
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/?foo"
  },
  {
    "caseIndex": 128,
    "pattern": [
      {
        "hash": ":café"
      }
    ],
    "input": {
      "hash": "foo"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {
        "café": "foo"
      },
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/#foo"
  },
  {
    "caseIndex": 129,
    "pattern": [
      {
        "protocol": ":℘"
      }
    ],
    "input": {
      "protocol": "foo"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {
        "℘": "foo"
      },
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/"
  },
  {
    "caseIndex": 130,
    "pattern": [
      {
        "username": ":℘"
      }
    ],
    "input": {
      "username": "foo"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {
        "℘": "foo"
      },
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://foo@example.com/"
  },
  {
    "caseIndex": 131,
    "pattern": [
      {
        "password": ":℘"
      }
    ],
    "input": {
      "password": "foo"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {
        "℘": "foo"
      },
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://:foo@example.com/"
  },
  {
    "caseIndex": 132,
    "pattern": [
      {
        "hostname": ":℘"
      }
    ],
    "input": {
      "hostname": "foo"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {
        "℘": "foo"
      },
      "port": {}
    },
    "expectedUrl": "http://foo/"
  },
  {
    "caseIndex": 133,
    "pattern": [
      {
        "pathname": "/:℘"
      }
    ],
    "input": {
      "pathname": "/foo"
    },
    "params": {
      "pathname": {
        "℘": "foo"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo"
  },
  {
    "caseIndex": 134,
    "pattern": [
      {
        "search": ":℘"
      }
    ],
    "input": {
      "search": "foo"
    },
    "params": {
      "pathname": {},
      "search": {
        "℘": "foo"
      },
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/?foo"
  },
  {
    "caseIndex": 135,
    "pattern": [
      {
        "hash": ":℘"
      }
    ],
    "input": {
      "hash": "foo"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {
        "℘": "foo"
      },
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/#foo"
  },
  {
    "caseIndex": 136,
    "pattern": [
      {
        "protocol": ":㐀"
      }
    ],
    "input": {
      "protocol": "foo"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {
        "㐀": "foo"
      },
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/"
  },
  {
    "caseIndex": 137,
    "pattern": [
      {
        "username": ":㐀"
      }
    ],
    "input": {
      "username": "foo"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {
        "㐀": "foo"
      },
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://foo@example.com/"
  },
  {
    "caseIndex": 138,
    "pattern": [
      {
        "password": ":㐀"
      }
    ],
    "input": {
      "password": "foo"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {
        "㐀": "foo"
      },
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://:foo@example.com/"
  },
  {
    "caseIndex": 139,
    "pattern": [
      {
        "hostname": ":㐀"
      }
    ],
    "input": {
      "hostname": "foo"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {
        "㐀": "foo"
      },
      "port": {}
    },
    "expectedUrl": "http://foo/"
  },
  {
    "caseIndex": 140,
    "pattern": [
      {
        "pathname": "/:㐀"
      }
    ],
    "input": {
      "pathname": "/foo"
    },
    "params": {
      "pathname": {
        "㐀": "foo"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo"
  },
  {
    "caseIndex": 141,
    "pattern": [
      {
        "search": ":㐀"
      }
    ],
    "input": {
      "search": "foo"
    },
    "params": {
      "pathname": {},
      "search": {
        "㐀": "foo"
      },
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/?foo"
  },
  {
    "caseIndex": 142,
    "pattern": [
      {
        "hash": ":㐀"
      }
    ],
    "input": {
      "hash": "foo"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {
        "㐀": "foo"
      },
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/#foo"
  },
  {
    "caseIndex": 144,
    "pattern": [
      {
        "protocol": "(.*)"
      }
    ],
    "input": {
      "protocol": "cafe"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {
        "0": "cafe"
      },
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/"
  },
  {
    "caseIndex": 145,
    "pattern": [
      {
        "protocol": "foo-bar"
      }
    ],
    "input": {
      "protocol": "foo-bar"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/"
  },
  {
    "caseIndex": 146,
    "pattern": [
      {
        "username": "caf%C3%A9"
      }
    ],
    "input": {
      "username": "café"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://caf%C3%A9@example.com/"
  },
  {
    "caseIndex": 147,
    "pattern": [
      {
        "username": "café"
      }
    ],
    "input": {
      "username": "café"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://caf%C3%A9@example.com/"
  },
  {
    "caseIndex": 149,
    "pattern": [
      {
        "password": "caf%C3%A9"
      }
    ],
    "input": {
      "password": "café"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://:caf%C3%A9@example.com/"
  },
  {
    "caseIndex": 150,
    "pattern": [
      {
        "password": "café"
      }
    ],
    "input": {
      "password": "café"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://:caf%C3%A9@example.com/"
  },
  {
    "caseIndex": 152,
    "pattern": [
      {
        "hostname": "xn--caf-dma.com"
      }
    ],
    "input": {
      "hostname": "café.com"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://xn--caf-dma.com/"
  },
  {
    "caseIndex": 153,
    "pattern": [
      {
        "hostname": "café.com"
      }
    ],
    "input": {
      "hostname": "café.com"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://xn--caf-dma.com/"
  },
  {
    "caseIndex": 154,
    "pattern": [
      "http://🚲.com/"
    ],
    "input": "http://🚲.com/",
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://xn--h78h.com/"
  },
  {
    "caseIndex": 160,
    "pattern": [
      {
        "pathname": "test/:a𐑐b"
      }
    ],
    "input": {
      "pathname": "test/foo"
    },
    "params": {
      "pathname": {
        "a𐑐b": "foo"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/test/foo"
  },
  {
    "caseIndex": 162,
    "pattern": [
      {
        "port": ""
      }
    ],
    "input": {
      "protocol": "http",
      "port": "80"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {
        "0": "http"
      },
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/"
  },
  {
    "caseIndex": 163,
    "pattern": [
      {
        "protocol": "http",
        "port": "80"
      }
    ],
    "input": {
      "protocol": "http",
      "port": "80"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/"
  },
  {
    "caseIndex": 169,
    "pattern": [
      {
        "port": "80"
      }
    ],
    "input": {
      "port": "80"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/"
  },
  {
    "caseIndex": 170,
    "pattern": [
      {
        "port": "80"
      }
    ],
    "input": {
      "port": "8\t0"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/"
  },
  {
    "caseIndex": 171,
    "pattern": [
      {
        "port": "80"
      }
    ],
    "input": {
      "port": "80x"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/"
  },
  {
    "caseIndex": 172,
    "pattern": [
      {
        "port": "80"
      }
    ],
    "input": {
      "port": "80?x"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/"
  },
  {
    "caseIndex": 173,
    "pattern": [
      {
        "port": "80"
      }
    ],
    "input": {
      "port": "80\\x"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/"
  },
  {
    "caseIndex": 175,
    "pattern": [
      {
        "pathname": "/foo/bar"
      }
    ],
    "input": {
      "pathname": "/foo/./bar"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo/bar"
  },
  {
    "caseIndex": 176,
    "pattern": [
      {
        "pathname": "/foo/baz"
      }
    ],
    "input": {
      "pathname": "/foo/bar/../baz"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo/baz"
  },
  {
    "caseIndex": 177,
    "pattern": [
      {
        "pathname": "/caf%C3%A9"
      }
    ],
    "input": {
      "pathname": "/café"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/caf%C3%A9"
  },
  {
    "caseIndex": 178,
    "pattern": [
      {
        "pathname": "/café"
      }
    ],
    "input": {
      "pathname": "/café"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/caf%C3%A9"
  },
  {
    "caseIndex": 181,
    "pattern": [
      {
        "pathname": "/foo/bar"
      }
    ],
    "input": {
      "pathname": "foo/bar",
      "baseURL": "https://example.com"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {
        "0": "https"
      },
      "hostname": {
        "0": "example.com"
      },
      "port": {}
    },
    "expectedUrl": "https://example.com/foo/bar"
  },
  {
    "caseIndex": 182,
    "pattern": [
      {
        "pathname": "/foo/../bar"
      }
    ],
    "input": {
      "pathname": "/bar"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/bar"
  },
  {
    "caseIndex": 183,
    "pattern": [
      {
        "pathname": "./foo/bar",
        "baseURL": "https://example.com"
      }
    ],
    "input": {
      "pathname": "foo/bar",
      "baseURL": "https://example.com"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "https://example.com/foo/bar"
  },
  {
    "caseIndex": 184,
    "pattern": [
      {
        "pathname": "",
        "baseURL": "https://example.com"
      }
    ],
    "input": {
      "pathname": "/",
      "baseURL": "https://example.com"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "https://example.com/"
  },
  {
    "caseIndex": 187,
    "pattern": [
      {
        "pathname": "b",
        "baseURL": "https://example.com/foo/"
      }
    ],
    "input": {
      "pathname": "./b",
      "baseURL": "https://example.com/foo/"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "https://example.com/b"
  },
  {
    "caseIndex": 189,
    "pattern": [
      {
        "pathname": "foo/bar",
        "baseURL": "https://example.com"
      }
    ],
    "input": "https://example.com/foo/bar",
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "https://example.com/foo/bar"
  },
  {
    "caseIndex": 190,
    "pattern": [
      {
        "pathname": ":name.html",
        "baseURL": "https://example.com"
      }
    ],
    "input": "https://example.com/foo.html",
    "params": {
      "pathname": {
        "name": "foo"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "https://example.com/foo.html"
  },
  {
    "caseIndex": 191,
    "pattern": [
      {
        "search": "q=caf%C3%A9"
      }
    ],
    "input": {
      "search": "q=café"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/?q=caf%C3%A9"
  },
  {
    "caseIndex": 192,
    "pattern": [
      {
        "search": "q=café"
      }
    ],
    "input": {
      "search": "q=café"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/?q=caf%C3%A9"
  },
  {
    "caseIndex": 194,
    "pattern": [
      {
        "hash": "caf%C3%A9"
      }
    ],
    "input": {
      "hash": "café"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/#caf%C3%A9"
  },
  {
    "caseIndex": 195,
    "pattern": [
      {
        "hash": "café"
      }
    ],
    "input": {
      "hash": "café"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/#caf%C3%A9"
  },
  {
    "caseIndex": 200,
    "pattern": [
      {
        "pathname": "/foo!"
      }
    ],
    "input": {
      "pathname": "/foo!"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo!"
  },
  {
    "caseIndex": 201,
    "pattern": [
      {
        "pathname": "/foo\\:"
      }
    ],
    "input": {
      "pathname": "/foo:"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo:"
  },
  {
    "caseIndex": 202,
    "pattern": [
      {
        "pathname": "/foo\\{"
      }
    ],
    "input": {
      "pathname": "/foo{"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo%7B"
  },
  {
    "caseIndex": 203,
    "pattern": [
      {
        "pathname": "/foo\\("
      }
    ],
    "input": {
      "pathname": "/foo("
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo("
  },
  {
    "caseIndex": 204,
    "pattern": [
      {
        "protocol": "javascript",
        "pathname": "var x = 1;"
      }
    ],
    "input": {
      "protocol": "javascript",
      "pathname": "var x = 1;"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/var%20x%20=%201;"
  },
  {
    "caseIndex": 206,
    "pattern": [
      {
        "protocol": "javascript",
        "pathname": "var x = 1;"
      }
    ],
    "input": {
      "baseURL": "javascript:var x = 1;"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "javascript:var x = 1;"
  },
  {
    "caseIndex": 209,
    "pattern": [
      {
        "pathname": "var x = 1;"
      }
    ],
    "input": {
      "pathname": "var x = 1;"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/var%20x%20=%201;"
  },
  {
    "caseIndex": 210,
    "pattern": [
      {
        "pathname": "/foo/bar"
      }
    ],
    "input": "./foo/bar",
    "baseURL": "https://example.com",
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {
        "0": "https"
      },
      "hostname": {
        "0": "example.com"
      },
      "port": {}
    },
    "expectedUrl": "https://example.com/foo/bar"
  },
  {
    "caseIndex": 211,
    "pattern": [
      {
        "pathname": "/foo/bar"
      }
    ],
    "input": {
      "pathname": "/foo/bar"
    },
    "baseURL": "https://example.com",
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "https://example.com/foo/bar"
  },
  {
    "caseIndex": 212,
    "pattern": [
      "https://example.com:8080/foo?bar#baz"
    ],
    "input": {
      "pathname": "/foo",
      "search": "bar",
      "hash": "baz",
      "baseURL": "https://example.com:8080"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "https://example.com:8080/foo?bar#baz"
  },
  {
    "caseIndex": 213,
    "pattern": [
      "/foo?bar#baz",
      "https://example.com:8080"
    ],
    "input": {
      "pathname": "/foo",
      "search": "bar",
      "hash": "baz",
      "baseURL": "https://example.com:8080"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "https://example.com:8080/foo?bar#baz"
  },
  {
    "caseIndex": 216,
    "pattern": [
      "http{s}?://{*.}?example.com/:product/:endpoint"
    ],
    "input": "https://sub.example.com/foo/bar",
    "params": {
      "pathname": {
        "product": "foo",
        "endpoint": "bar"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {
        "0": "sub"
      },
      "port": {}
    },
    "expectedUrl": "https://sub.example.com/foo/bar"
  },
  {
    "caseIndex": 217,
    "pattern": [
      "https://example.com?foo"
    ],
    "input": "https://example.com/?foo",
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "https://example.com/?foo"
  },
  {
    "caseIndex": 218,
    "pattern": [
      "https://example.com#foo"
    ],
    "input": "https://example.com/#foo",
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "https://example.com/#foo"
  },
  {
    "caseIndex": 219,
    "pattern": [
      "https://example.com:8080?foo"
    ],
    "input": "https://example.com:8080/?foo",
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "https://example.com:8080/?foo"
  },
  {
    "caseIndex": 220,
    "pattern": [
      "https://example.com:8080#foo"
    ],
    "input": "https://example.com:8080/#foo",
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "https://example.com:8080/#foo"
  },
  {
    "caseIndex": 221,
    "pattern": [
      "https://example.com/?foo"
    ],
    "input": "https://example.com/?foo",
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "https://example.com/?foo"
  },
  {
    "caseIndex": 222,
    "pattern": [
      "https://example.com/#foo"
    ],
    "input": "https://example.com/#foo",
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "https://example.com/#foo"
  },
  {
    "caseIndex": 224,
    "pattern": [
      "https://example.com/*\\?foo"
    ],
    "input": "https://example.com/?foo",
    "params": {
      "pathname": {
        "0": ""
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "https://example.com/?foo"
  },
  {
    "caseIndex": 226,
    "pattern": [
      "https://example.com/:name\\?foo"
    ],
    "input": "https://example.com/bar?foo",
    "params": {
      "pathname": {
        "name": "bar"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "https://example.com/bar?foo"
  },
  {
    "caseIndex": 230,
    "pattern": [
      "https://example.com/{bar}\\?foo"
    ],
    "input": "https://example.com/bar?foo",
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "https://example.com/bar?foo"
  },
  {
    "caseIndex": 233,
    "pattern": [
      "data\\:foobar"
    ],
    "input": "data:foobar",
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "data:foobar"
  },
  {
    "caseIndex": 234,
    "pattern": [
      "https://{sub.}?example.com/foo"
    ],
    "input": "https://example.com/foo",
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "https://example.com/foo"
  },
  {
    "caseIndex": 235,
    "pattern": [
      "https://{sub.}?example{.com/}foo"
    ],
    "input": "https://example.com/foo",
    "params": {
      "pathname": {
        "0": "/foo"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "https://example.com/foo"
  },
  {
    "caseIndex": 242,
    "pattern": [
      "file:///foo/bar"
    ],
    "input": "file:///foo/bar",
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "file:///foo/bar"
  },
  {
    "caseIndex": 243,
    "pattern": [
      "data:"
    ],
    "input": "data:",
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "data:"
  },
  {
    "caseIndex": 247,
    "pattern": [
      {
        "protocol": "http{s}?:",
        "search": "?bar",
        "hash": "#baz"
      }
    ],
    "input": "http://example.com/foo?bar#baz",
    "params": {
      "pathname": {
        "0": "/foo"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {
        "0": "example.com"
      },
      "port": {}
    },
    "expectedUrl": "http://example.com/foo?bar#baz"
  },
  {
    "caseIndex": 248,
    "pattern": [
      "?bar#baz",
      "https://example.com/foo"
    ],
    "input": "?bar#baz",
    "baseURL": "https://example.com/foo",
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "https://example.com/foo?bar#baz"
  },
  {
    "caseIndex": 249,
    "pattern": [
      "?bar",
      "https://example.com/foo#baz"
    ],
    "input": "?bar",
    "baseURL": "https://example.com/foo#snafu",
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "https://example.com/foo?bar"
  },
  {
    "caseIndex": 250,
    "pattern": [
      "#baz",
      "https://example.com/foo?bar"
    ],
    "input": "#baz",
    "baseURL": "https://example.com/foo?bar",
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "https://example.com/foo?bar#baz"
  },
  {
    "caseIndex": 251,
    "pattern": [
      "#baz",
      "https://example.com/foo"
    ],
    "input": "#baz",
    "baseURL": "https://example.com/foo",
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "https://example.com/foo#baz"
  },
  {
    "caseIndex": 254,
    "pattern": [
      "https://foo\\:bar@example.com"
    ],
    "input": "https://foo:bar@example.com",
    "params": {
      "pathname": {
        "0": "/"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "https://foo:bar@example.com/"
  },
  {
    "caseIndex": 255,
    "pattern": [
      "https://foo@example.com"
    ],
    "input": "https://foo@example.com",
    "params": {
      "pathname": {
        "0": "/"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "https://foo@example.com/"
  },
  {
    "caseIndex": 256,
    "pattern": [
      "https://\\:bar@example.com"
    ],
    "input": "https://:bar@example.com",
    "params": {
      "pathname": {
        "0": "/"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "https://:bar@example.com/"
  },
  {
    "caseIndex": 257,
    "pattern": [
      "https://:user::pass@example.com"
    ],
    "input": "https://foo:bar@example.com",
    "params": {
      "pathname": {
        "0": "/"
      },
      "search": {},
      "hash": {},
      "username": {
        "user": "foo"
      },
      "password": {
        "pass": "bar"
      },
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "https://foo:bar@example.com/"
  },
  {
    "caseIndex": 258,
    "pattern": [
      "https\\:foo\\:bar@example.com"
    ],
    "input": "https:foo:bar@example.com",
    "params": {
      "pathname": {
        "0": "/"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "https://foo:bar@example.com/"
  },
  {
    "caseIndex": 259,
    "pattern": [
      "data\\:foo\\:bar@example.com"
    ],
    "input": "data:foo:bar@example.com",
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "data:foo:bar@example.com"
  },
  {
    "caseIndex": 261,
    "pattern": [
      "data{\\:}channel.html",
      "https://example.com"
    ],
    "input": "https://example.com/data:channel.html",
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "https://example.com/data:channel.html"
  },
  {
    "caseIndex": 262,
    "pattern": [
      "http://[\\:\\:1]/"
    ],
    "input": "http://[::1]/",
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://[::1]/"
  },
  {
    "caseIndex": 263,
    "pattern": [
      "http://[\\:\\:1]:8080/"
    ],
    "input": "http://[::1]:8080/",
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://[::1]:8080/"
  },
  {
    "caseIndex": 264,
    "pattern": [
      "http://[\\:\\:a]/"
    ],
    "input": "http://[::a]/",
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://[::a]/"
  },
  {
    "caseIndex": 265,
    "pattern": [
      "http://[:address]/"
    ],
    "input": "http://[::1]/",
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {
        "address": "::1"
      },
      "port": {}
    },
    "expectedUrl": "http://[::1]/"
  },
  {
    "caseIndex": 266,
    "pattern": [
      "http://[\\:\\:AB\\::num]/"
    ],
    "input": "http://[::ab:1]/",
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {
        "num": "1"
      },
      "port": {}
    },
    "expectedUrl": "http://[::ab:1]/"
  },
  {
    "caseIndex": 267,
    "pattern": [
      {
        "hostname": "[\\:\\:AB\\::num]"
      }
    ],
    "input": {
      "hostname": "[::ab:1]"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {
        "num": "1"
      },
      "port": {}
    },
    "expectedUrl": "http://[::ab:1]/"
  },
  {
    "caseIndex": 269,
    "pattern": [
      {
        "hostname": "{[\\:\\:ab\\::num]}"
      }
    ],
    "input": {
      "hostname": "[::ab:1]"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {
        "num": "1"
      },
      "port": {}
    },
    "expectedUrl": "http://[::ab:1]/"
  },
  {
    "caseIndex": 271,
    "pattern": [
      {
        "hostname": "{[\\:\\::num\\:1]}"
      }
    ],
    "input": {
      "hostname": "[::ab:1]"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {
        "num": "ab"
      },
      "port": {}
    },
    "expectedUrl": "http://[::ab:1]/"
  },
  {
    "caseIndex": 273,
    "pattern": [
      {
        "hostname": "[*\\:1]"
      }
    ],
    "input": {
      "hostname": "[::ab:1]"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {
        "0": "::ab"
      },
      "port": {}
    },
    "expectedUrl": "http://[::ab:1]/"
  },
  {
    "caseIndex": 277,
    "pattern": [
      "data\\:text/javascript,let x = 100/:tens?5;"
    ],
    "input": "data:text/javascript,let x = 100/5;",
    "params": {
      "pathname": {
        "tens": null
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "data:text/javascript,let x = 100/5;"
  },
  {
    "caseIndex": 282,
    "pattern": [
      {
        "pathname": ":name*"
      }
    ],
    "input": {
      "pathname": "foobar"
    },
    "params": {
      "pathname": {
        "name": "foobar"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foobar"
  },
  {
    "caseIndex": 283,
    "pattern": [
      {
        "pathname": ":name+"
      }
    ],
    "input": {
      "pathname": "foobar"
    },
    "params": {
      "pathname": {
        "name": "foobar"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foobar"
  },
  {
    "caseIndex": 284,
    "pattern": [
      {
        "pathname": ":name"
      }
    ],
    "input": {
      "pathname": "foobar"
    },
    "params": {
      "pathname": {
        "name": "foobar"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foobar"
  },
  {
    "caseIndex": 285,
    "pattern": [
      {
        "protocol": ":name*"
      }
    ],
    "input": {
      "protocol": "foobar"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {
        "name": "foobar"
      },
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/"
  },
  {
    "caseIndex": 286,
    "pattern": [
      {
        "protocol": ":name+"
      }
    ],
    "input": {
      "protocol": "foobar"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {
        "name": "foobar"
      },
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/"
  },
  {
    "caseIndex": 287,
    "pattern": [
      {
        "protocol": ":name"
      }
    ],
    "input": {
      "protocol": "foobar"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {
        "name": "foobar"
      },
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/"
  },
  {
    "caseIndex": 289,
    "pattern": [
      {
        "hostname": "bad#hostname"
      }
    ],
    "input": {
      "hostname": "bad"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://bad/"
  },
  {
    "caseIndex": 291,
    "pattern": [
      {
        "hostname": "bad/hostname"
      }
    ],
    "input": {
      "hostname": "bad"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://bad/"
  },
  {
    "caseIndex": 302,
    "pattern": [
      {
        "hostname": "bad\nhostname"
      }
    ],
    "input": {
      "hostname": "badhostname"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://badhostname/"
  },
  {
    "caseIndex": 303,
    "pattern": [
      {
        "hostname": "bad\rhostname"
      }
    ],
    "input": {
      "hostname": "badhostname"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://badhostname/"
  },
  {
    "caseIndex": 304,
    "pattern": [
      {
        "hostname": "bad\thostname"
      }
    ],
    "input": {
      "hostname": "badhostname"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://badhostname/"
  },
  {
    "caseIndex": 305,
    "pattern": [
      {}
    ],
    "input": "https://example.com/",
    "params": {
      "pathname": {
        "0": "/"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {
        "0": "https"
      },
      "hostname": {
        "0": "example.com"
      },
      "port": {}
    },
    "expectedUrl": "https://example.com/"
  },
  {
    "caseIndex": 312,
    "pattern": [
      {
        "pathname": "{:foo}(.*)"
      }
    ],
    "input": {
      "pathname": "foobarbaz"
    },
    "params": {
      "pathname": {
        "0": "oobarbaz",
        "foo": "f"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foobarbaz"
  },
  {
    "caseIndex": 314,
    "pattern": [
      {
        "pathname": "{:foo}{(.*)}"
      }
    ],
    "input": {
      "pathname": "foobarbaz"
    },
    "params": {
      "pathname": {
        "0": "oobarbaz",
        "foo": "f"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foobarbaz"
  },
  {
    "caseIndex": 316,
    "pattern": [
      {
        "pathname": "{:foo}{bar(.*)}"
      }
    ],
    "input": {
      "pathname": "foobarbaz"
    },
    "params": {
      "pathname": {
        "0": "baz",
        "foo": "foo"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foobarbaz"
  },
  {
    "caseIndex": 317,
    "pattern": [
      {
        "pathname": "{:foo}:bar(.*)"
      }
    ],
    "input": {
      "pathname": "foobarbaz"
    },
    "params": {
      "pathname": {
        "foo": "f",
        "bar": "oobarbaz"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foobarbaz"
  },
  {
    "caseIndex": 318,
    "pattern": [
      {
        "pathname": "{:foo}?(.*)"
      }
    ],
    "input": {
      "pathname": "foobarbaz"
    },
    "params": {
      "pathname": {
        "0": "oobarbaz",
        "foo": "f"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foobarbaz"
  },
  {
    "caseIndex": 319,
    "pattern": [
      {
        "pathname": "{:foo\\bar}"
      }
    ],
    "input": {
      "pathname": "foobar"
    },
    "params": {
      "pathname": {
        "foo": "foo"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foobar"
  },
  {
    "caseIndex": 320,
    "pattern": [
      {
        "pathname": "{:foo\\.bar}"
      }
    ],
    "input": {
      "pathname": "foo.bar"
    },
    "params": {
      "pathname": {
        "foo": "foo"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo.bar"
  },
  {
    "caseIndex": 322,
    "pattern": [
      {
        "pathname": "{:foo}bar"
      }
    ],
    "input": {
      "pathname": "foobar"
    },
    "params": {
      "pathname": {
        "foo": "foo"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foobar"
  },
  {
    "caseIndex": 323,
    "pattern": [
      {
        "pathname": ":foo\\bar"
      }
    ],
    "input": {
      "pathname": "foobar"
    },
    "params": {
      "pathname": {
        "foo": "foo"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foobar"
  },
  {
    "caseIndex": 324,
    "pattern": [
      {
        "pathname": ":foo{}(.*)"
      }
    ],
    "input": {
      "pathname": "foobar"
    },
    "params": {
      "pathname": {
        "0": "oobar",
        "foo": "f"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foobar"
  },
  {
    "caseIndex": 325,
    "pattern": [
      {
        "pathname": ":foo{}bar"
      }
    ],
    "input": {
      "pathname": "foobar"
    },
    "params": {
      "pathname": {
        "foo": "foo"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foobar"
  },
  {
    "caseIndex": 326,
    "pattern": [
      {
        "pathname": ":foo{}?bar"
      }
    ],
    "input": {
      "pathname": "foobar"
    },
    "params": {
      "pathname": {
        "foo": "foo"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foobar"
  },
  {
    "caseIndex": 327,
    "pattern": [
      {
        "pathname": "*{}**?"
      }
    ],
    "input": {
      "pathname": "foobar"
    },
    "params": {
      "pathname": {
        "0": "foobar",
        "1": null
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foobar"
  },
  {
    "caseIndex": 330,
    "pattern": [
      {
        "pathname": "*/*"
      }
    ],
    "input": {
      "pathname": "foo/bar"
    },
    "params": {
      "pathname": {
        "0": "foo",
        "1": "bar"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo/bar"
  },
  {
    "caseIndex": 331,
    "pattern": [
      {
        "pathname": "*\\/*"
      }
    ],
    "input": {
      "pathname": "foo/bar"
    },
    "params": {
      "pathname": {
        "0": "foo",
        "1": "bar"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo/bar"
  },
  {
    "caseIndex": 332,
    "pattern": [
      {
        "pathname": "*/{*}"
      }
    ],
    "input": {
      "pathname": "foo/bar"
    },
    "params": {
      "pathname": {
        "0": "foo",
        "1": "bar"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo/bar"
  },
  {
    "caseIndex": 334,
    "pattern": [
      {
        "pathname": "/:foo."
      }
    ],
    "input": {
      "pathname": "/bar."
    },
    "params": {
      "pathname": {
        "foo": "bar"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/bar."
  },
  {
    "caseIndex": 335,
    "pattern": [
      {
        "pathname": "/:foo.."
      }
    ],
    "input": {
      "pathname": "/bar.."
    },
    "params": {
      "pathname": {
        "foo": "bar"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/bar.."
  },
  {
    "caseIndex": 336,
    "pattern": [
      {
        "pathname": "./foo"
      }
    ],
    "input": {
      "pathname": "./foo"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo"
  },
  {
    "caseIndex": 337,
    "pattern": [
      {
        "pathname": "../foo"
      }
    ],
    "input": {
      "pathname": "../foo"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/foo"
  },
  {
    "caseIndex": 338,
    "pattern": [
      {
        "pathname": ":foo./"
      }
    ],
    "input": {
      "pathname": "bar./"
    },
    "params": {
      "pathname": {
        "foo": "bar"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/bar./"
  },
  {
    "caseIndex": 339,
    "pattern": [
      {
        "pathname": ":foo../"
      }
    ],
    "input": {
      "pathname": "bar../"
    },
    "params": {
      "pathname": {
        "foo": "bar"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/bar../"
  },
  {
    "caseIndex": 340,
    "pattern": [
      {
        "pathname": "/:foo\\bar"
      }
    ],
    "input": {
      "pathname": "/bazbar"
    },
    "params": {
      "pathname": {
        "foo": "baz"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/bazbar"
  },
  {
    "caseIndex": 341,
    "pattern": [
      {
        "pathname": "/foo/bar"
      },
      {
        "ignoreCase": true
      }
    ],
    "input": {
      "pathname": "/FOO/BAR"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/FOO/BAR"
  },
  {
    "caseIndex": 342,
    "pattern": [
      {
        "ignoreCase": true
      }
    ],
    "input": {
      "pathname": "/FOO/BAR"
    },
    "params": {
      "pathname": {
        "0": "/FOO/BAR"
      },
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "http://example.com/FOO/BAR"
  },
  {
    "caseIndex": 343,
    "pattern": [
      "https://example.com:8080/foo?bar#baz",
      {
        "ignoreCase": true
      }
    ],
    "input": {
      "pathname": "/FOO",
      "search": "BAR",
      "hash": "BAZ",
      "baseURL": "https://example.com:8080"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "https://example.com:8080/FOO?BAR#BAZ"
  },
  {
    "caseIndex": 344,
    "pattern": [
      "/foo?bar#baz",
      "https://example.com:8080",
      {
        "ignoreCase": true
      }
    ],
    "input": {
      "pathname": "/FOO",
      "search": "BAR",
      "hash": "BAZ",
      "baseURL": "https://example.com:8080"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "https://example.com:8080/FOO?BAR#BAZ"
  },
  {
    "caseIndex": 346,
    "pattern": [
      {
        "search": "foo",
        "baseURL": "https://example.com/a/+/b"
      }
    ],
    "input": {
      "search": "foo",
      "baseURL": "https://example.com/a/+/b"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "https://example.com/a/+/b?foo"
  },
  {
    "caseIndex": 347,
    "pattern": [
      {
        "hash": "foo",
        "baseURL": "https://example.com/?q=*&v=?&hmm={}&umm=()"
      }
    ],
    "input": {
      "hash": "foo",
      "baseURL": "https://example.com/?q=*&v=?&hmm={}&umm=()"
    },
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "https://example.com/?q=*&v=?&hmm={}&umm=()#foo"
  },
  {
    "caseIndex": 348,
    "pattern": [
      "#foo",
      "https://example.com/?q=*&v=?&hmm={}&umm=()"
    ],
    "input": "https://example.com/?q=*&v=?&hmm={}&umm=()#foo",
    "params": {
      "pathname": {},
      "search": {},
      "hash": {},
      "username": {},
      "password": {},
      "protocol": {},
      "hostname": {},
      "port": {}
    },
    "expectedUrl": "https://example.com/?q=*&v=?&hmm={}&umm=()#foo"
  }
] as const;
